spring.application.name=NasaApi

# H2 Database
spring.datasource.url=jdbc:h2:mem:nasa
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# JWT
app.jwt.secret=c2VncmVkby1zdXBlci1mb3J0ZS1wYXJhLWp3dC0xMjM0NTY3ODkwMTI=
app.jwt.expiration-ms=86400000

# NASA API
nasa.api.key=koj87Wwdqr3dWGamqXJdrmEffokrmCEEGmXcshuK
nasa.api.url=https://api.nasa.gov/planetary/apod

# Actuator (monitoramento)
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when-authorized

# Logging
logging.level.br.com.ramos.nasaapi=DEBUG
logging.level.org.springframework.security=INFO
