spring.application.name=NasaApi
spring.datasource.url=jdbc:h2:mem:nasa
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


nasa.api.key=koj87Wwdqr3dWGamqXJdrmEffokrmCEEGmXcshuK
nasa.api.url=https://api.nasa.gov/planetary/apod
spring.h2.console.enabled=true